### ISSUE TITLE
Instalando requirements.txt en Windows

### ISSUE THREAD

**Issue by ajlopez** [mgaitan/preciosa#127]
Al tratar de ejecutar

```
pip install -r requirements.txt
```

en un Windows 8, luego de instalar virtualenv, y haberlo activado, me da un error. Paso la parte parece importante del pip.log

```
No distributions matching the version for argparse==1.2.1 (from -r requirements.txt (line 10))
Exception information:
Traceback (most recent call last):
  File "D:\Virtual Machines\preciosa_ve\lib\site-packages\pip\basecommand.py", line 122, in main
    status = self.run(options, args)
  File "D:\Virtual Machines\preciosa_ve\lib\site-packages\pip\commands\install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "D:\Virtual Machines\preciosa_ve\lib\site-packages\pip\req.py", line 1177, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "D:\Virtual Machines\preciosa_ve\lib\site-packages\pip\index.py", line 322, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for argparse==1.2.1 (from -r requirements.txt (line 10))

```

**Comment by matuu** [comment]
No tengo mucha experiencia con python en windows, pero si te bajar el paquete [0] y lo instalas con <code>python setup install</code> ?
[0] http://argparse.googlecode.com/files/argparse-1.2.1.tar.gz
Más info: https://pypi.python.org/pypi/argparse

**Comment by mgaitan** [comment]
Angel, probá 2 cosas.
- que estás usando python 2.7
- borrá argparse del requirements.txt .  Si funca, mandá un PR please.

argparse es parte de la stdlib en python actuales.  no sé bien por qué está
ahi.

PD: Hay que hacer urgente el ticket #77

On Tue, Feb 25, 2014 at 9:11 PM, Matias Varela notifications@github.comwrote:

> No tengo mucha experiencia con python en windows, pero si te bajar el
> paquete [0] y lo instalas con python setup install ?
> [0] http://argparse.googlecode.com/files/argparse-1.2.1.tar.gz
> Más info: https://pypi.python.org/pypi/argparse
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/mgaitan/preciosa/issues/127#issuecomment-36075778
> .

## 

mgaitan.github.io
textosyprextextos.com.ar

**Comment by ajlopez** [comment]
Bien, si, estaba usando python 2.7, lo tuve que agregar manualmente en ese momento a mi path

Ahora probe en otra maquina Windows Server 2008, sacar el argparse del requirements. Pero ahora da

```
A critical module was not found. Probably this operating system does not
support it. Pexpect is intended for UNIX-like operating systems.
```

El tema es pexpect... no se si se usa o se puede sacar del requirement?
