### ISSUE TITLE
Generación de base de datos

### ISSUE THREAD

**Issue by ajlopez** [mgaitan/preciosa#90]
Estoy ahora en una maquina Windows 2008 Server. Uso Python 2.7 (no encontre que version de Python necesitan)

Cuando siguiendo INSTALL.md llego a

```
python manage.py syncdb
```

tuve dos problemas:

1) no encontraba django.core.management, tuve que instalarlo dentro de virtualenv con

```
pip install Django
```

2) luego me da

```
(preciosa_ve) C:\Git\preciosa>python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    startup.run()
  File "C:\Git\preciosa\preciosa\startup.py", line 20, in run
    autoload(["receivers"])
  File "C:\Git\preciosa\preciosa\startup.py", line 10, in autoload
    mod = import_module(app)
  File "C:\Git\preciosa\preciosa_ve\lib\site-packages\django\utils\importlib.py"
, line 40, in import_module
    __import__(name)
ImportError: No module named bootstrapform
```

y ahi no se que hacer

**Comment by mgaitan** [comment]
On Tue, Feb 18, 2014 at 8:50 AM, ajlopez notifications@github.com wrote:

> 1) no encontraba django.core.management, tuve que instalarlo dentro de
> virtualenv con
> 
> pip install Django
> 
> todas las dependencias están listadas en requirements.txt

para instalarlas, **con el virtualenv activado** tenés que hacer

pip install -r requriments.txt

PD: no está claro eso en el install ? /me nunca lo revisó, ja!

## 

mgaitan.github.io
textosyprextextos.com.ar

**Comment by ajlopez** [comment]
Ah! Me olvide de aclarar. YA HABIA HECHO

pip install -r requirements.txt

e instalo parva de cosas

Pero cuando fui a 

python manage.py syncdb

no encontro eso del django.core.nosecuanto ;-)

No hice entonces pip list, asi que no se si estaba o no estaba django y como. Pero hice

pip install Django

y al volver al manager.py, me dio el stack trace que mencione

No se si es general, o es en Windows (que es donde yo probe)

**Comment by mgaitan** [comment]
2014-02-18 13:43 GMT-03:00 ajlopez notifications@github.com:

> Ah! Me olvide de aclarar. YA HABIA HECHO
> 
> pip install -r requirements.txt
> 
> e instalo parva de cosas
> 
> Pero cuando fui a
> 
> python manage.py syncdb
> 
> no encontro eso del django.core.nosecuanto ;-)

Seguramente instalaste _todo_ fuera del virtualenv. Es decir, te olvidaste
o algo falló en la activación antes.

o algo anda mal con windows, no sé, no tengo el gusto (?).

¿alguien puede ayudar?

PD: Ángel, cono todo lo que sabe usted, como es que sigue trabajando en
windows? (no es chicana, es curiosidad).

## 

mgaitan.github.io
textosyprextextos.com.ar
